---
name: Docker Build and Push to GitHub Container Registry
inputs:
  username:  # id of input
    description: 'Username'
  password:
    description: 'Password' 
runs:
    using: "composite"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # username: ${{ github.repository_owner }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

