---
  name: Docker Build and Push to GitHub Container Registry
  
  on:
    push:
      branches:
        - main
  
  jobs:
    build-and-push:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
        - name: Replace placeholder inside YAML with actual image
          run: |
            yq e -i '.spec.template.spec.containers[0].image = "ghcr.io/${{ github.repository }}:${{ github.sha }}"' kubernetes/deployment.yaml
            cat kubernetes/deployment.yaml
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
        - name: Install EKS Cluster configuration
          run: aws eks --region us-west-2 update-kubeconfig --name eks-cluster
        - name: Install kubectl inside the runner
          uses: azure/setup-kubectl@v3
        - name: Deploy to cluster
          run: kubectl apply -f kubernetes/deployment.yaml
  